In [1]:
import numpy as np

In [2]:
#hier matrix ändern um ihre SVD zu berechnen
matrix = np.array([[-2.6, 3, -5.2],[4, 10, -3],[6.8, 4, 2.6]]) 

u,s,v_trans = np.linalg.svd(matrix)

sigma = np.zeros(matrix.shape)
np.fill_diagonal(sigma,s)
print("u:")
print(u)
print("sigma:")
print(sigma)
print("v tans:")
print(v_trans)
print("ursprüngliche Matrix:")
print(np.dot(u, np.dot(sigma,v_trans)))

u:
[[ 0.16789993 -0.7342431   0.65779684]
 [ 0.85511515 -0.22353101 -0.46777342]
 [ 0.4904974   0.64103117  0.59033155]]
sigma:
[[12.8834589   0.          0.        ]
 [ 0.          8.38324283  0.        ]
 [ 0.          0.          0.73329827]]
v tans:
[[ 0.4904974   0.85511515 -0.16789993]
 [ 0.64103117 -0.22353101  0.7342431 ]
 [ 0.59033155 -0.46777342 -0.65779684]]
ursprüngliche Matrix:
[[-2.6  3.  -5.2]
 [ 4.  10.  -3. ]
 [ 6.8  4.   2.6]]
